# Generated by Django 5.0.6 on 2024-11-07 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_productosvendido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productosvendido',
            name='nombre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto'),
        ),
    ]
