# Generated by Django 5.0.6 on 2025-01-28 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_bodega_existenciasbodegas_existenciastienda'),
    ]

    operations = [
        migrations.CreateModel(
            name='Iteracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_iteracion', models.IntegerField(verbose_name='Número de Iteración')),
                ('orden_entrega', models.IntegerField(verbose_name='Orden de Entrega')),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.bodega', verbose_name='Bodega')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Iteración',
                'verbose_name_plural': 'Iteraciones',
                'ordering': ['numero_iteracion', 'orden_entrega'],
                'unique_together': {('numero_iteracion', 'producto', 'bodega')},
            },
        ),
    ]
