# Generated by Django 5.0.6 on 2025-01-28 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_iteracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='iteracion',
            name='completada',
            field=models.BooleanField(default=False),
        ),
    ]
