# Generated by Django 5.0.6 on 2025-01-28 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_iteracion_completada'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferenciaHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('fecha_transferencia', models.DateTimeField(auto_now_add=True)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.bodega')),
                ('iteracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.iteracion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
            ],
            options={
                'verbose_name': 'Historial de Transferencia',
                'verbose_name_plural': 'Historial de Transferencias',
                'ordering': ['-fecha_transferencia'],
            },
        ),
    ]
