# Generated by Django 5.0.6 on 2025-02-13 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_alter_iteracion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferenciahistorial',
            name='fecha_transferencia',
            field=models.DateTimeField(),
        ),
    ]
