# Generated by Django 5.0.6 on 2025-05-21 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_alter_transferenciahistorial_fecha_transferencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='tipo',
            field=models.CharField(choices=[('CIMEX', 'CIMEX'), ('TRD', 'TRD')], default='TRD', max_length=10),
        ),
    ]
