# Generated by Django 5.0.6 on 2025-05-21 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0013_tienda_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Circunscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('ancianos', models.PositiveIntegerField(default=0, help_text='Número de personas de la tercera edad', verbose_name='Ancianos')),
                ('ninos', models.PositiveIntegerField(default=0, help_text='Número de niños', verbose_name='Niños')),
                ('discapacitados', models.PositiveIntegerField(default=0, help_text='Número de personas con discapacidad', verbose_name='Discapacitados')),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circunscripciones', to='inventario.bodega', verbose_name='Bodega asociada')),
            ],
            options={
                'verbose_name': 'Circunscripción',
                'verbose_name_plural': 'Circunscripciones',
                'ordering': ['nombre'],
            },
        ),
    ]
