# Generated by Django 4.2.21 on 2025-05-22 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0014_circunscripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circunscripcion',
            name='bodega',
        ),
        migrations.RemoveField(
            model_name='circunscripcion',
            name='discapacitados',
        ),
        migrations.AddField(
            model_name='circunscripcion',
            name='embarazadas',
            field=models.PositiveIntegerField(default=0, help_text='Número de mujeres embarazadas', verbose_name='Embarazadas'),
        ),
        migrations.AlterField(
            model_name='bodega',
            name='cp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.circunscripcion'),
        ),
    ]
