# Generated by Django 4.2.21 on 2025-05-22 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0015_remove_circunscripcion_bodega_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodega',
            name='cantidad_nucleos',
            field=models.IntegerField(default=0),
        ),
    ]
