# Generated by Django 4.2.21 on 2025-05-31 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0016_bodega_cantidad_nucleos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='cantidad',
        ),
    ]
