# Generated by Django 4.2.21 on 2025-06-01 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0017_remove_producto_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='primera_necesidad',
            field=models.BooleanField(default=False),
        ),
    ]
