# Generated by Django 4.2.21 on 2025-06-01 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0018_producto_primera_necesidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaAcciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CREATE', 'Crear'), ('UPDATE', 'Actualizar'), ('DELETE', 'Eliminar'), ('VIEW', 'Ver'), ('TRANSFER', 'Transferir'), ('LOGIN', 'Iniciar Sesión'), ('LOGOUT', 'Cerrar Sesión'), ('SEARCH', 'Buscar'), ('EXPORT', 'Exportar'), ('IMPORT', 'Importar')], max_length=20)),
                ('modelo', models.CharField(help_text='Nombre del modelo afectado', max_length=100)),
                ('objeto_id', models.CharField(blank=True, help_text='ID del objeto afectado', max_length=100, null=True)),
                ('objeto_nombre', models.CharField(blank=True, help_text='Nombre/descripción del objeto', max_length=200, null=True)),
                ('descripcion', models.TextField(help_text='Descripción detallada de la acción')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('datos_adicionales', models.JSONField(blank=True, help_text='Datos adicionales en formato JSON', null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auditoría de Acción',
                'verbose_name_plural': 'Auditorías de Acciones',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
