# Generated by Django 4.2.21 on 2025-06-01 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0019_auditoriaacciones'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditoriaacciones',
            options={'ordering': ['-fecha_hora'], 'verbose_name': 'Auditoría de Acción', 'verbose_name_plural': 'Auditoría'},
        ),
        migrations.AddField(
            model_name='transferenciahistorial',
            name='tienda_destino',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='inventario.tienda'),
        ),
    ]
